imagenet_templates = [
    ' An abstract painting of {}.',
    'A stunning natural {} painting is created by the artist Paul Cezanne in a post-impressionism style.',
    'A painting of {} by Joaquin Sorolla',
    'A {} by Bruce Pennington.',
    'An oil paninting of {} in impressionism style.',
    'a photo of the hard to see {}.',
    'A pencil drawing of a {}.',
    'A pencil sketch of a {}.',
    'graffiti of a {}.',
    'This baroque {} painting was drawn by Juan van der Hamen.',
    'A cartoon painting of a {}',
    'A look up at the stars painting of {}.',
    'the embroidered {}.',
    'a photo of a hard to see {}.',
    'a bright photo of a {}.',
    'a photo of a clean {}.',
    'a photo of a dirty {}.',
    'a dark photo of the {}.',
    'a drawing of a {}.',
    'a photo of my {}.',
    'the plastic {}.',
    'a photo of the cool {}.',
    'a close-up photo of a {}.',
    'a black and white photo of the {}.',
    'a painting of the {}.',
    'a painting of a {}.',
    'a pixelated photo of the {}.',
    'a sculpture of the {}.',
    'a bright photo of the {}.',
    'a cropped photo of a {}.',
    'a plastic {}.',
    'a photo of the dirty {}.',
    'a jpeg corrupted photo of a {}.',
    'a blurry photo of the {}.',
    'a photo of the {}.',
    'a good photo of the {}.',
    'a rendering of the {}.',
    'a {} in a video game.',
    'a photo of one {}.',
    'a doodle of a {}.',
    'a close-up photo of the {}.',
    'a photo of a {}.',
    'the origami {}.',
    'the {} in a video game.',
    'a sketch of a {}.',
    'a doodle of the {}.',
    'a origami {}.',
    'a low resolution photo of a {}.',
    'the toy {}.',
    'a rendition of the {}.',
    'a photo of the clean {}.',
    'a photo of a large {}.',
    'a rendition of a {}.',
    'a photo of a nice {}.',
    'a photo of a weird {}.',
    'a blurry photo of a {}.',
    'a cartoon {}.',
    'art of a {}.',
    'a sketch of the {}.',
    'a embroidered {}.',
    'a pixelated photo of a {}.',
    'itap of the {}.',
    'a jpeg corrupted photo of the {}.',
    'a good photo of a {}.',
    'a plushie {}.',
    'a photo of the nice {}.',
    'a photo of the small {}.',
    'a photo of the weird {}.',
    'the cartoon {}.',
    'art of the {}.',
    'a drawing of the {}.',
    'a photo of the large {}.',
    'a black and white photo of a {}.',
    'An ukiyo-e painting of {}.',
    'a dark photo of a {}.',
    'itap of a {}.',
    'This is a colorful painting of urban {} in the styler of cubism and futurism',
    'An monochromatic painting of a {}.',
    'An colorful painting of a {}.',
    'An monochromatic painting of a {}.',
]
